config/routes.rb
Rails.application.routes.draw do

  get 'people/show'

  get 'search/index'

  get 'home/index'

  resources :movies, only: :show
  resources :people, only: :show

  match "search", to: "search#index", via: :get

  # You can have the root of your site routed with "root"
  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  require 'themoviedb'

  before_filter :set_config

  Tmdb::Api.key("8a221fc31fcdf12a8af827465574ffc9")

  def set_config
   @configuration = Tmdb::Configuration.new
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@now_playing = Tmdb::Movie.now_playing
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    @movie = Tmdb::Movie.detail(params[:id])
    @images = Tmdb::Movie.images(params[:id])
    @cast = Tmdb::Movie.casts(params[:id])
    @trailers = Tmdb::Movie.trailers(params[:id])
    @similar_movies = Tmdb::Movie.similar_movies(params[:id])
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show

 	@people = Tmdb::Person.detail(params[:id])
  	@movies = Tmdb::Person.credits(params[:id])

  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
	@movie = Tmdb::Movie.find(params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  TmdbConfiguration = Tmdb::Configuration.new

  # <%= image_tag("#{@configuration.base_url}w154#{image['file_path']}") if image['file_path'] %>
  # <%= image_tag("#{@configuration.base_url}w92#{movie['poster_path']}") if movie['poster_path'] %>
  def movie_poster(path)
    if path
      image_tag("#{TmdbConfiguration.base_url}w154#{path}")
    else
      ""
    end
  end

  # <%= image_tag("#{@configuration.base_url}w300#{cast['profile_path']}") if cast['profile_path'] %>
  def cast_poster(path)
    if path
      image_tag("#{TmdbConfiguration.base_url}w300#{path}")
    else
      ""
    end
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/index.html.erb
<div id="layout" class="pure-g">
  

  <div class="sidebar pure-u-1 pure-u-med-1-4">
    <div class="header2">
      <hgroup>
      <h2 class="movie-tittle">
		<div class="search_title">Search for a movie</div>
		<center><%= form_tag("/search", :method => "get") do %>
  		<%= text_field_tag(:query, nil, :class => "input-xlarge searchInput") %></center>
		<% end %>
      </h2>
      </hgroup>
    </div>
  </div>
</div>

  <div class="content pure-u-1 pure-u-med-3-4">
	<div class="posts">
        <h1 class="content-subhead">  
          Now Playing
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            		<% @now_playing.first(15).each do |movie| %>
			<% if movie %>
				<%= link_to movie_path(movie['id']) do %>
					<%= image_tag("#{@configuration.base_url}w154#{movie['poster_path']}") if movie['poster_path'] %>
				<% end %>
			<% end %>
		<% end %>
          </div> 
          </div>
        </section>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMovies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/movies/show.html.erb
  <div id="layout" class="pure-g">
  

  <div class="sidebar pure-u-1 pure-u-med-1-4">

      <h1 class="movie-tittle"><%= @movie.title %></h1>
      <div class="srodeczek"><%= image_tag("#{@configuration.base_url}w154#{@movie.poster_path}") if @movie.poster_path %></div>
    <div class="header">
      <hgroup>
      <h2 class="brand-tagline">
      <table class="pure-table">
        <tr><td>Budget:</td><td> $<%= number_with_delimiter(@movie.budget, :delimiter => ',') %></td></tr>
        <tr><td>Revenue:</td><td> $<%= number_with_delimiter(@movie.revenue, :delimiter => ',') %></td></tr>
        <tr><td>Status:</td><td> <%= @movie.status %></td></tr>
        <tr><td>Runtime:</td><td> <%= @movie.runtime %></td></tr>
        <tr><td>Release Date:</td><td> <%= @movie.release_date.to_date.strftime("%d/%m/%Y") if @movie.release_date %></td></tr>
      </table>
      </h2>
      </hgroup>
    </div>
  </div>

  <div class="content pure-u-1 pure-u-med-3-4">
    <div class="posts">
      <% @trailers['youtube'].each do |trailer| %>
        <h1 class="content-subhead">  
          Trailer
        </h1>
        <section class="post">
          <div class="post-description">
              <%= link_to "#{trailer['name']} - #{trailer['size']}", "http://www.youtube.com/watch?v=#{trailer['source']}" %>
          </div>
        </section>
      <% end %>
    </div>

    <div class="posts">
        <h1 class="content-subhead">  
          Rating
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            <div id="star" data-score="<%= @movie.vote_average %>"></div>
            <p><%= @movie.vote_average %> from <%= @movie.vote_count %> voters.</p>
          </div> 
          </div>
        </section>
    </div>


    <div class="posts">
        <h1 class="content-subhead">  
          Overview
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            <p><%= @movie.overview %></p>
          </div> 
          </div>
        </section>
    </div>

    <div class="posts">
        <h1 class="content-subhead">  
          Tagline
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            <p><%= @movie.tagline %></p>
          </div> 
          </div>
        </section>
    </div>


    <div class="posts">
        <h1 class="content-subhead">  
          Genres
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            <p><p><% @movie.genres.each do |genre| %>
              <%= genre['name'] %>
            <% end %></p>
          </div> 
          </div>
        </section>
    </div>


    <div class="posts">
        <h1 class="content-subhead">  
          Posters
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            <% @images['posters'].each_with_index do |image| %>
              <%= image_tag("#{@configuration.base_url}w154#{image['file_path']}") if image['file_path'] %>
             <% end %>
            </div> 
          </div>
        </section>
    </div>


    <div class="posts">
        <h1 class="content-subhead">  
          Backdrops
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            <% @images['backdrops'].each_with_index do |image| %>
              <%= image_tag("#{@configuration.base_url}w154#{image['file_path']}") if image['file_path'] %>
             <% end %>
            </div> 
          </div>
        </section>
    </div>


    <div class="posts">
        <h1 class="content-subhead">  
          Casts
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            <table class="malusi">
            <% @cast.first(5).each do |cast| %>
            <tr>
              <td>
                <%= cast_poster cast['profile_path'] %>
                <% unless cast['profile_path'] %>
                  <img src="http://placehold.it/154x154">
                <% end %>
              </td>
              <td>
                <%= link_to cast['name'], person_path(cast['id']) %> as <%= cast['character'] %>
              </td>
            </tr>
            <% end %>
          </table>
          </div> 
          </div>
        </section>
    </div>

    <div class="posts">
        <h1 class="content-subhead">  
        Similar Movies
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
                <% if @similar_movies %>
                 <div>
                   <% @similar_movies.first(8).each do |movie| %>
                     <% if movie %>
                        <%= link_to movie_path(movie['id']) do %>
                          <%= movie_poster movie['poster_path'] %>
                        <% end %>
                     <% end %>
                   <% end %>
                <% end %>
          </div> 
          </div>
        </section>
    </div>


    </div> 

</div>
</div>

</div>

app/views/people/show.html.erb
<div id="layout" class="pure-g">
  

  <div class="sidebar pure-u-1 pure-u-med-1-4">

      <h1 class="movie-tittle"><%= @people.name %></h1>
      <div class="srodeczek">      <%= image_tag("#{@configuration.base_url}w154#{@people.profile_path}") if @people.profile_path %></div>
    <div class="header">
      <hgroup>
      <h2 class="brand-tagline">
        <table class="pure-table">
          <tr><td>Born:</td><td> <%= @people.place_of_birth %></td></tr>
          <tr><td>Birthday:</td><td> <%= @people.birthday %></td></tr>
        </table>
      </h2>
      </hgroup>
    </div>
  </div>

  <div class="content pure-u-1 pure-u-med-3-4">
    <div class="posts">
        <h1 class="content-subhead">  
          Biography
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            <%= @people.biography %>
          </div> 
          </div>
        </section>
    </div>

    <div class="posts">
        <h1 class="content-subhead">  
          Homepage
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
            <%= link_to @people.homepage, @people.homepage %>
          </div> 
          </div>
        </section>
    </div>

    <div class="posts">
        <h1 class="content-subhead">  
          Known for
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
                  <% @movies['cast'].first(7).each do |movie| %>
        <%= link_to movie_path(movie['id']) do %>
          <%= image_tag("#{@configuration.base_url}w92#{movie['poster_path']}") if movie['poster_path'] %>
        <% end %>
      <% end %>
          </div> 
          </div>
        </section>
    </div>

app/views/search/index.html.erb
<div id="layout" class="pure-g">
  

  <div class="sidebar pure-u-1 pure-u-med-1-4">
    <div class="header2">
      <hgroup>
      <h2 class="movie-tittle">
		<div class="search_title">Search results</div>
      </h2>
      </hgroup>
    </div>
  </div>
</div>

  <div class="content pure-u-1 pure-u-med-3-4">

	<% @movie.each do |movie| %>
	<div class="posts">
        <h1 class="content-subhead">  
          <%= link_to movie.title, movie_path(movie.id) %> (<%= movie.release_date.to_date.strftime("%Y") %>)
        </h1>
        <section class="post">
          <div class="post-description">
           <div>
           	<div class="srodeczek">
				<%= link_to movie_path(movie.id) do %>
					<%= image_tag("#{@configuration.base_url}w154#{movie.poster_path}") if movie.poster_path %>
				<% end %>
			</div>

			Directors: <% Tmdb::Movie.crew(movie.id).each do |crew| %> <% if crew['department'] == 'Directing' %> <%= link_to crew['name'], person_path(crew['id']) %> <% end %><% end %><br />
							Writers:
							Starring: <% Tmdb::Movie.casts(movie.id).first(3).each do |cast| %> <%= link_to cast['name'], person_path(cast['id']) %> | <% end %>
          </div> 
          </div>
        </section>
    </div>
    <% end %>

  </div>
</div>